// +build !ios

package main

/*
#cgo CFLAGS: -pipe -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB 
#cgo CXXFLAGS: -pipe -stdlib=libc++ -O2 -std=gnu++11 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_DESIGNER_LIB -DQT_UIPLUGIN_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB 
#cgo CXXFLAGS: -I../../qt-recipe -I. -I/usr/local/Cellar/qt/5.10.1/lib/QtMultimediaWidgets.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtDesigner.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtUiPlugin.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtQuickWidgets.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtQuick.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtQml.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtDBus.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtXml.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtTest.framework/Headers -I/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.10.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.10.1/lib
#cgo LDFLAGS: -stdlib=libc++ -headerpad_max_install_names -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks
#cgo LDFLAGS:  -F/usr/local/Cellar/qt/5.10.1/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework QtDesigner -framework QtXml -framework QtQuickWidgets -framework QtQuick -framework QtQml -framework QtDBus -framework QtTest -framework Security -framework Foundation -framework ApplicationServices -framework OpenGL -framework AGL
*/
import "C"
